vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    sondage_images:
      uri_prefix: '%app.path.sondage_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.sondage_images%'